### ISSUE TITLE
Rendering error

### ISSUE THREAD

**Issue by rajkumaar23** [obedm503/katex-latex#19] opened 2020-03-26 07:48 UTC
Can someone help me with why the below data isn't rendered properly by the extension ?
## My config : 
```
extensions: [
        showdownKatex({
            throwOnError: true,
            errorColor: '#1500ff',
            macros: {
                href: "{}"
            },
            delimiters: [
                {left: "$", right: "$", display: false},
                {left: "\(", right: '\)', display: false},
                {left: "$$", right: "$$", display: true},
                {left: "\[", right: '\]', display: true},
            ],
        }),
    ],
```

## The data : 
```
### Read problem statements in [Hindi](http://www.codechef.com/download/translated/APRIL19/hindi/XORMIN.pdf), [Bengali](http://www.codechef.com/download/translated/APRIL19/bengali/XORMIN.pdf), [Mandarin Chinese](http://www.codechef.com/download/translated/APRIL19/mandarin/XORMIN.pdf), [Russian](http://www.codechef.com/download/translated/APRIL19/russian/XORMIN.pdf), and [Vietnamese](http://www.codechef.com/download/translated/APRIL19/vietnamese/XORMIN.pdf) as well.<br /><br />You are given a rooted tree with $N$ vertices (numbered $1$ through $N$); vertex $1$ is the root. Each vertex has a weight; let's denote the weight of vertex $i$ by $w_i$.<br /><br />You should answer $Q$ queries. The queries have to be processed online, i.e. to obtain each query, you need the answer to the previous query.<br /><br />In each query, you are given a vertex $v$ and a parameter $k$. For each vertex $u$ in the subtree of $v$ (including $v$), consider the value $w_u \oplus k$ ($\oplus$ denotes the bitwise XOR operation). The answer to this query is the maximum of these values and the smallest $u$ such that vertex $u$ is in the subtree of vertex $v$ and $w_u \oplus k$ is equal to this maximum.<br /><br />### Input<br />- The first line of the input contains a single integer $T$ denoting the number of test cases. The description of $T$ test cases follows.<br />- The first line of each test case contains two space-separated integers $N$ and $Q$.<br />- The second line contains $N$ space-separated integers $w_1, w_2, \ldots, w_N$.<br />- Each of the next $N-1$ lines contains two space-separated integers $x$ and $y$ denoting that there is an edge between nodes $x$ and $y$.<br />- The next $Q$ lines describe queries. Each of these lines contains two space-separated integers $a$ and $b$. The parameters $v$ and $k$ can be obtained in the following way: let's denote the value and vertex from the answer to the previous query by $x_l$ and $v_l$ respectively ($x_l = v_l = 0$ if this is the first query); then, $v = a \oplus v_l$ and $k = b \oplus x_l$.<br /><br />### Output<br />For each query, print a single line containing two space-separated integers — the answer to the query, i.e. the number of the vertex for which we get the maximum value and the maximum value.<br /><br />### Constraints <br />- $1 \le T \le 1,000$<br />- $1 \le N \le 2 \cdot 10^5$<br />- $1 \le Q \le 10^6$<br />- $1 \le x, y, v \le N$<br />- $1 \le w_i \lt 2^{20}$ for each valid $i$<br />- $1 \le k \lt 2^{20}$<br />- the sum of $N$ over all test cases does not exceed $2 \cdot 10^5$<br />- the sum of $Q$ over all test cases does not exceed $10^6$<br /><br />### Subtasks<br />**Subtask #1 (10 points):**<br />- the sum of $N$ over all test cases does not exceed $5,000$<br />- the sum of $Q$ over all test cases does not exceed $5,000$<br /><br />**Subtask #2 (15 points):**<br />- the sum of $N$ over all test cases does not exceed $2,000$<br />- the sum of $Q$ over all test cases does not exceed $10^6$<br /><br />**Subtask #3 (75 points):** original constraints<br /><br />### Example Input<br />```<br />1<br />10 5<br />9 17 93 16 3 61 23 11 2 1<br />1 2<br />2 5<br />5 8<br />1 3<br />1 4<br />3 6<br />3 7<br />6 9<br />6 10<br />4 14<br />7 123<br />5 103<br />9 32<br />5 118<br />```<br /><br />### Example Output<br />```<br />4 30<br />7 114<br />8 30<br />3 99<br />6 40<br />```<br />
```

## Output : 
![image](https://user-images.githubusercontent.com/37476886/77622251-eef99180-6f63-11ea-9f64-b074ef0cbbec.png)

**Comment by obedm503** [comment] 2020-03-26 20:21
What is the issue specifically?

**Comment by rajkumaar23** [comment] 2020-03-27 05:27
If you look at this line :  `You are given a rooted tree with $N$ vertices`, it is rendered with two **N's**

### I'm not sure if this issue, but I need help on how to make the output look like this :

![image](https://user-images.githubusercontent.com/37476886/77724678-971d6200-7019-11ea-9a5d-40fe6c7316b0.png)

**Comment by obedm503** [comment] 2020-03-27 13:54
I'm unable to reproduce the problem. In fact, [testing in the sandbox](https://obedm503.github.io/showdown-katex/?source=You+are+given+a+rooted+tree+with+%24%24N%24%24+vertices) works perfectly fine. And testing the whole input from the first post [works just as well](https://obedm503.github.io/showdown-katex/?source=%0A%23%23%23+Read+problem+statements+in+%5BHindi%5D%28http%3A%2F%2Fwww.codechef.com%2Fdownload%2Ftranslated%2FAPRIL19%2Fhindi%2FXORMIN.pdf%29%2C+%5BBengali%5D%28http%3A%2F%2Fwww.codechef.com%2Fdownload%2Ftranslated%2FAPRIL19%2Fbengali%2FXORMIN.pdf%29%2C+%5BMandarin+Chinese%5D%28http%3A%2F%2Fwww.codechef.com%2Fdownload%2Ftranslated%2FAPRIL19%2Fmandarin%2FXORMIN.pdf%29%2C+%5BRussian%5D%28http%3A%2F%2Fwww.codechef.com%2Fdownload%2Ftranslated%2FAPRIL19%2Frussian%2FXORMIN.pdf%29%2C+and+%5BVietnamese%5D%28http%3A%2F%2Fwww.codechef.com%2Fdownload%2Ftranslated%2FAPRIL19%2Fvietnamese%2FXORMIN.pdf%29+as+well.%3Cbr+%2F%3E%3Cbr+%2F%3EYou+are+given+a+rooted+tree+with+%24%24N%24%24+vertices+%28numbered+%24%241%24%24+through+%24%24N%24%24%29%3B+vertex+%24%241%24%24+is+the+root.+Each+vertex+has+a+weight%3B+let%27s+denote+the+weight+of+vertex+%24%24i%24%24+by+%24%24w_i%24%24.%3Cbr+%2F%3E%3Cbr+%2F%3EYou+should+answer+%24%24Q%24%24+queries.+The+queries+have+to+be+processed+online%2C+i.e.+to+obtain+each+query%2C+you+need+the+answer+to+the+previous+query.%3Cbr+%2F%3E%3Cbr+%2F%3EIn+each+query%2C+you+are+given+a+vertex+%24%24v%24%24+and+a+parameter+%24%24k%24%24.+For+each+vertex+%24%24u%24%24+in+the+subtree+of+%24%24v%24%24+%28including+%24%24v%24%24%29%2C+consider+the+value+%24%24w_u+%5Coplus+k%24%24+%28%24%24%5Coplus%24%24+denotes+the+bitwise+XOR+operation%29.+The+answer+to+this+query+is+the+maximum+of+these+values+and+the+smallest+%24%24u%24%24+such+that+vertex+%24%24u%24%24+is+in+the+subtree+of+vertex+%24%24v%24%24+and+%24%24w_u+%5Coplus+k%24%24+is+equal+to+this+maximum.%3Cbr+%2F%3E%3Cbr+%2F%3E%23%23%23+Input%3Cbr+%2F%3E-+The+first+line+of+the+input+contains+a+single+integer+%24%24T%24%24+denoting+the+number+of+test+cases.+The+description+of+%24%24T%24%24+test+cases+follows.%3Cbr+%2F%3E-+The+first+line+of+each+test+case+contains+two+space-separated+integers+%24%24N%24%24+and+%24%24Q%24%24.%3Cbr+%2F%3E-+The+second+line+contains+%24%24N%24%24+space-separated+integers+%24%24w_1%2C+w_2%2C+%5Cldots%2C+w_N%24%24.%3Cbr+%2F%3E-+Each+of+the+next+%24%24N-1%24%24+lines+contains+two+space-separated+integers+%24%24x%24%24+and+%24%24y%24%24+denoting+that+there+is+an+edge+between+nodes+%24%24x%24%24+and+%24%24y%24%24.%3Cbr+%2F%3E-+The+next+%24%24Q%24%24+lines+describe+queries.+Each+of+these+lines+contains+two+space-separated+integers+%24%24a%24%24+and+%24%24b%24%24.+The+parameters+%24%24v%24%24+and+%24%24k%24%24+can+be+obtained+in+the+following+way%3A+let%27s+denote+the+value+and+vertex+from+the+answer+to+the+previous+query+by+%24%24x_l%24%24+and+%24%24v_l%24%24+respectively+%28%24%24x_l+%3D+v_l+%3D+0%24%24+if+this+is+the+first+query%29%3B+then%2C+%24%24v+%3D+a+%5Coplus+v_l%24%24+and+%24%24k+%3D+b+%5Coplus+x_l%24%24.%3Cbr+%2F%3E%3Cbr+%2F%3E%23%23%23+Output%3Cbr+%2F%3EFor+each+query%2C+print+a+single+line+containing+two+space-separated+integers+%E2%80%94+the+answer+to+the+query%2C+i.e.+the+number+of+the+vertex+for+which+we+get+the+maximum+value+and+the+maximum+value.%3Cbr+%2F%3E%3Cbr+%2F%3E%23%23%23+Constraints+%3Cbr+%2F%3E-+%24%241+%5Cle+T+%5Cle+1%2C000%24%24%3Cbr+%2F%3E-+%24%241+%5Cle+N+%5Cle+2+%5Ccdot+10%5E5%24%24%3Cbr+%2F%3E-+%24%241+%5Cle+Q+%5Cle+10%5E6%24%24%3Cbr+%2F%3E-+%24%241+%5Cle+x%2C+y%2C+v+%5Cle+N%24%24%3Cbr+%2F%3E-+%24%241+%5Cle+w_i+%5Clt+2%5E%7B20%7D%24%24+for+each+valid+%24%24i%24%24%3Cbr+%2F%3E-+%24%241+%5Cle+k+%5Clt+2%5E%7B20%7D%24%24%3Cbr+%2F%3E-+the+sum+of+%24%24N%24%24+over+all+test+cases+does+not+exceed+%24%242+%5Ccdot+10%5E5%24%24%3Cbr+%2F%3E-+the+sum+of+%24%24Q%24%24+over+all+test+cases+does+not+exceed+%24%2410%5E6%24%24%3Cbr+%2F%3E%3Cbr+%2F%3E%23%23%23+Subtasks%3Cbr+%2F%3E**Subtask+%231+%2810+points%29%3A**%3Cbr+%2F%3E-+the+sum+of+%24%24N%24%24+over+all+test+cases+does+not+exceed+%24%245%2C000%24%24%3Cbr+%2F%3E-+the+sum+of+%24%24Q%24%24+over+all+test+cases+does+not+exceed+%24%245%2C000%24%24%3Cbr+%2F%3E%3Cbr+%2F%3E**Subtask+%232+%2815+points%29%3A**%3Cbr+%2F%3E-+the+sum+of+%24%24N%24%24+over+all+test+cases+does+not+exceed+%24%242%2C000%24%24%3Cbr+%2F%3E-+the+sum+of+%24%24Q%24%24+over+all+test+cases+does+not+exceed+%24%2410%5E6%24%24%3Cbr+%2F%3E%3Cbr+%2F%3E**Subtask+%233+%2875+points%29%3A**+original+constraints%3Cbr+%2F%3E%3Cbr+%2F%3E%23%23%23+Example+Input%3Cbr+%2F%3E%60%60%60%3Cbr+%2F%3E1%3Cbr+%2F%3E10+5%3Cbr+%2F%3E9+17+93+16+3+61+23+11+2+1%3Cbr+%2F%3E1+2%3Cbr+%2F%3E2+5%3Cbr+%2F%3E5+8%3Cbr+%2F%3E1+3%3Cbr+%2F%3E1+4%3Cbr+%2F%3E3+6%3Cbr+%2F%3E3+7%3Cbr+%2F%3E6+9%3Cbr+%2F%3E6+10%3Cbr+%2F%3E4+14%3Cbr+%2F%3E7+123%3Cbr+%2F%3E5+103%3Cbr+%2F%3E9+32%3Cbr+%2F%3E5+118%3Cbr+%2F%3E%60%60%60%3Cbr+%2F%3E%3Cbr+%2F%3E%23%23%23+Example+Output%3Cbr+%2F%3E%60%60%60%3Cbr+%2F%3E4+30%3Cbr+%2F%3E7+114%3Cbr+%2F%3E8+30%3Cbr+%2F%3E3+99%3Cbr+%2F%3E6+40%3Cbr+%2F%3E%60%60%60%3Cbr+%2F%3E%0A) (just replacing `$` with `$$` since it's the default delimiter).

Please provide a complete html file that correctly demonstrates the issue, so I can verify if it is an issue with the extension.

**Comment by rajkumaar23** [comment] 2020-03-27 16:31
![Untitled](https://user-images.githubusercontent.com/37476886/77777043-f3619f80-7074-11ea-80cc-1929ae8bd53f.png)

### Please find the complete HTML file [here](https://github.com/obedm503/showdown-katex/files/4394786/test.html.tar.gz)

**Comment by rajkumaar23** [comment] 2020-03-27 16:47
Please find the complete HTML [here](https://github.com/obedm503/showdown-katex/files/4394856/test.tar.gz). The ones like 
![image](https://user-images.githubusercontent.com/37476886/77779579-c1ead300-7078-11ea-8590-e02ec6ef87ca.png)
aren't rendered properly.

**Comment by obedm503** [comment] 2020-03-27 20:29
Checked the file, no idea what it is. Can you post the markdown source? You can wrap it in triple back-ticks like below.

    ```markdown
    # markdown title

    markdown here $E=mc^2$
    ```

**Comment by rajkumaar23** [comment] 2020-03-28 03:43
```
### Read problem statements in [Hindi](http://www.codechef.com/download/translated/APRIL19/hindi/XORMIN.pdf), [Bengali](http://www.codechef.com/download/translated/APRIL19/bengali/XORMIN.pdf), [Mandarin Chinese](http://www.codechef.com/download/translated/APRIL19/mandarin/XORMIN.pdf), [Russian](http://www.codechef.com/download/translated/APRIL19/russian/XORMIN.pdf), and [Vietnamese](http://www.codechef.com/download/translated/APRIL19/vietnamese/XORMIN.pdf) as well.  

You are given a rooted tree with $N$ vertices (numbered $1$ through $N$); vertex $1$ is the root. Each vertex has a weight; let's denote the weight of vertex $i$ by $w_i$.  

You should answer $Q$ queries. The queries have to be processed online, i.e. to obtain each query, you need the answer to the previous query.  

In each query, you are given a vertex $v$ and a parameter $k$. For each vertex $u$ in the subtree of $v$ (including $v$), consider the value $w_u \oplus k$ ($\oplus$ denotes the bitwise XOR operation). The answer to this query is the maximum of these values and the smallest $u$ such that vertex $u$ is in the subtree of vertex $v$ and $w_u \oplus k$ is equal to this maximum.  

### Input  
- The first line of the input contains a single integer $T$ denoting the number of test cases. The description of $T$ test cases follows.  
- The first line of each test case contains two space-separated integers $N$ and $Q$.  
- The second line contains $N$ space-separated integers $w_1, w_2, \ldots, w_N$.  
- Each of the next $N-1$ lines contains two space-separated integers $x$ and $y$ denoting that there is an edge between nodes $x$ and $y$.  
- The next $Q$ lines describe queries. Each of these lines contains two space-separated integers $a$ and $b$. The parameters $v$ and $k$ can be obtained in the following way: let's denote the value and vertex from the answer to the previous query by $x_l$ and $v_l$ respectively ($x_l = v_l = 0$ if this is the first query); then, $v = a \oplus v_l$ and $k = b \oplus x_l$.  

### Output  
For each query, print a single line containing two space-separated integers — the answer to the query, i.e. the number of the vertex for which we get the maximum value and the maximum value.  

### Constraints  
- $1 \le T \le 1,000$  
- $1 \le N \le 2 \cdot 10^5$  
- $1 \le Q \le 10^6$  
- $1 \le x, y, v \le N$  
- $1 \le w_i \lt 2^{20}$ for each valid $i$  
- $1 \le k \lt 2^{20}$  
- the sum of $N$ over all test cases does not exceed $2 \cdot 10^5$  
- the sum of $Q$ over all test cases does not exceed $10^6$  

### Subtasks  
**Subtask #1 (10 points):**  
- the sum of $N$ over all test cases does not exceed $5,000$  
- the sum of $Q$ over all test cases does not exceed $5,000$  

**Subtask #2 (15 points):**  
- the sum of $N$ over all test cases does not exceed $2,000$  
- the sum of $Q$ over all test cases does not exceed $10^6$  

**Subtask #3 (75 points):** original constraints  
```

**Comment by obedm503** [comment] 2020-03-28 19:23
Tried reproducing the issue in 2 ways: replaced `$` with `$$`, and tried using the configuration given in the first post. Still could not reproduce it.

First screenshot is by replacing `$` with `$$`. Here's a [link to the working demo](https://obedm503.github.io/showdown-katex/?source=%23%23%23+Read+problem+statements+in+%5BHindi%5D%28http%3A%2F%2Fwww.codechef.com%2Fdownload%2Ftranslated%2FAPRIL19%2Fhindi%2FXORMIN.pdf%29%2C+%5BBengali%5D%28http%3A%2F%2Fwww.codechef.com%2Fdownload%2Ftranslated%2FAPRIL19%2Fbengali%2FXORMIN.pdf%29%2C+%5BMandarin+Chinese%5D%28http%3A%2F%2Fwww.codechef.com%2Fdownload%2Ftranslated%2FAPRIL19%2Fmandarin%2FXORMIN.pdf%29%2C+%5BRussian%5D%28http%3A%2F%2Fwww.codechef.com%2Fdownload%2Ftranslated%2FAPRIL19%2Frussian%2FXORMIN.pdf%29%2C+and+%5BVietnamese%5D%28http%3A%2F%2Fwww.codechef.com%2Fdownload%2Ftranslated%2FAPRIL19%2Fvietnamese%2FXORMIN.pdf%29+as+well.++%0A%0AYou+are+given+a+rooted+tree+with+%24%24N%24%24+vertices+%28numbered+%24%241%24%24+through+%24%24N%24%24%29%3B+vertex+%24%241%24%24+is+the+root.+Each+vertex+has+a+weight%3B+let%27s+denote+the+weight+of+vertex+%24%24i%24%24+by+%24%24w_i%24%24.++%0A%0AYou+should+answer+%24%24Q%24%24+queries.+The+queries+have+to+be+processed+online%2C+i.e.+to+obtain+each+query%2C+you+need+the+answer+to+the+previous+query.++%0A%0AIn+each+query%2C+you+are+given+a+vertex+%24%24v%24%24+and+a+parameter+%24%24k%24%24.+For+each+vertex+%24%24u%24%24+in+the+subtree+of+%24%24v%24%24+%28including+%24%24v%24%24%29%2C+consider+the+value+%24%24w_u+%5Coplus+k%24%24+%28%24%24%5Coplus%24%24+denotes+the+bitwise+XOR+operation%29.+The+answer+to+this+query+is+the+maximum+of+these+values+and+the+smallest+%24%24u%24%24+such+that+vertex+%24%24u%24%24+is+in+the+subtree+of+vertex+%24%24v%24%24+and+%24%24w_u+%5Coplus+k%24%24+is+equal+to+this+maximum.++%0A%0A%23%23%23+Input++%0A-+The+first+line+of+the+input+contains+a+single+integer+%24%24T%24%24+denoting+the+number+of+test+cases.+The+description+of+%24%24T%24%24+test+cases+follows.++%0A-+The+first+line+of+each+test+case+contains+two+space-separated+integers+%24%24N%24%24+and+%24%24Q%24%24.++%0A-+The+second+line+contains+%24%24N%24%24+space-separated+integers+%24%24w_1%2C+w_2%2C+%5Cldots%2C+w_N%24%24.++%0A-+Each+of+the+next+%24%24N-1%24%24+lines+contains+two+space-separated+integers+%24%24x%24%24+and+%24%24y%24%24+denoting+that+there+is+an+edge+between+nodes+%24%24x%24%24+and+%24%24y%24%24.++%0A-+The+next+%24%24Q%24%24+lines+describe+queries.+Each+of+these+lines+contains+two+space-separated+integers+%24%24a%24%24+and+%24%24b%24%24.+The+parameters+%24%24v%24%24+and+%24%24k%24%24+can+be+obtained+in+the+following+way%3A+let%27s+denote+the+value+and+vertex+from+the+answer+to+the+previous+query+by+%24%24x_l%24%24+and+%24%24v_l%24%24+respectively+%28%24%24x_l+%3D+v_l+%3D+0%24%24+if+this+is+the+first+query%29%3B+then%2C+%24%24v+%3D+a+%5Coplus+v_l%24%24+and+%24%24k+%3D+b+%5Coplus+x_l%24%24.++%0A%0A%23%23%23+Output++%0AFor+each+query%2C+print+a+single+line+containing+two+space-separated+integers+%E2%80%94+the+answer+to+the+query%2C+i.e.+the+number+of+the+vertex+for+which+we+get+the+maximum+value+and+the+maximum+value.++%0A%0A%23%23%23+Constraints++%0A-+%24%241+%5Cle+T+%5Cle+1%2C000%24%24++%0A-+%24%241+%5Cle+N+%5Cle+2+%5Ccdot+10%5E5%24%24++%0A-+%24%241+%5Cle+Q+%5Cle+10%5E6%24%24++%0A-+%24%241+%5Cle+x%2C+y%2C+v+%5Cle+N%24%24++%0A-+%24%241+%5Cle+w_i+%5Clt+2%5E%7B20%7D%24%24+for+each+valid+%24%24i%24%24++%0A-+%24%241+%5Cle+k+%5Clt+2%5E%7B20%7D%24%24++%0A-+the+sum+of+%24%24N%24%24+over+all+test+cases+does+not+exceed+%24%242+%5Ccdot+10%5E5%24%24++%0A-+the+sum+of+%24%24Q%24%24+over+all+test+cases+does+not+exceed+%24%2410%5E6%24%24++%0A%0A%23%23%23+Subtasks++%0A**Subtask+%231+%2810+points%29%3A**++%0A-+the+sum+of+%24%24N%24%24+over+all+test+cases+does+not+exceed+%24%245%2C000%24%24++%0A-+the+sum+of+%24%24Q%24%24+over+all+test+cases+does+not+exceed+%24%245%2C000%24%24++%0A%0A**Subtask+%232+%2815+points%29%3A**++%0A-+the+sum+of+%24%24N%24%24+over+all+test+cases+does+not+exceed+%24%242%2C000%24%24++%0A-+the+sum+of+%24%24Q%24%24+over+all+test+cases+does+not+exceed+%24%2410%5E6%24%24++%0A%0A**Subtask+%233+%2875+points%29%3A**+original+constraints).

![normal](https://user-images.githubusercontent.com/9118707/77831769-0faa1e80-70ff-11ea-82df-46b16208f9e6.png)

For the second screenshot, I kept the original text, but changed the extension config.
![custom](https://user-images.githubusercontent.com/9118707/77831801-50099c80-70ff-11ea-9657-537756d65344.png)

Still was not able to reproduce it. Will close the issue until the problem can be reproduced.

**Closed as completed by obedm503** 2020-03-28 19:23 UTC

**Comment by simonsandell** [comment] 2020-08-11 19:03
I had the same issue. It was solved by manually dowloading and including the katex css and fonts. I'm using Vue, not sure if there is a compatibility issue there or why katex css and fonts wasn't installed properly by `npm install --save showdown-katex`.
But now everything seems to be working smoothly, thanks for the cool package!
