### ISSUE TITLE
`$` block need to double `\` symbol to get the same effects of LaTeX formular

### ISSUE THREAD

**Issue by HowcanoeWang** [obedm503/katex-latex#21] opened 2020-05-31 12:37 UTC
As shown in the image captured from the demo webpage, https://obedm503.github.io/showdown-katex,  `$` formular need to double `\` to make it work

![screen shot](https://i.loli.net/2020/05/31/ZLkdtVigyB4v172.png)

Attach the codes below:

<pre>
### 1.  $ formular need to double `\` to make it work

For example
```latex
\left\{ \begin{array}{ccccc} 2x_1 & -x_2 & 1.5x_3 & = & 8 \\ x_1 & & -4x_3 & = & -7 \end{array} \right.
```

if what get the same effects in  in `$$$` `$$$` blocks, `\left\{` need to change to `\left\\{` and `\\` need to change to `\\\\`

$$\left\\{ \begin{array}{ccccc} 2x_1 & -x_2 & 1.5x_3 & = & 8 \\\\ x_1 & & -4x_3 & = & -7 \end{array} \right.$$  
</pre>

Alternatively, I have to use javascript to replace those strings in the website to make it work.
```javascript
var md_1 = md.replace(/\\{2}/g, "\\\\\\\\")
var md_2 = md_1.replace(/\\\{/g, "\\\\\{");
var md_3 = md_2.replace(/\\\}/g, "\\\\\}")
```

**Comment by obedm503** [comment] 2020-06-03 20:04
Thanks for the detailed report.

This is a bit of a tricky situation. This extension uses a [showdown `output` sub-extension](https://github.com/showdownjs/showdown/wiki/extensions#type-propertyrequired) to handle inline mode. By the time showdown calls the sub-extension the text has already been escaped. See the [showdown wiki](https://github.com/showdownjs/showdown/wiki/Showdown's-Markdown-syntax#escaping-markdown-entities) for a list of affected characters. Showdown will always convert `\{` to `{`.

This behavior may be a showdown bug where it always escapes these characters even when they're not involved in markdown syntax. So, `\[` is always converted to `[` even when no closing square bracket is found. I don't know if this is showdown's intended behavior. Perhaps opening an issue there may lead to a fix.

The other option would be to only use `lang` extensions. This would mean converting the extension from delegating to `katex.renderMathInElement` to handling everything locally: delimiters, ignoring anything inside code constructs, etc. I would rather not have to handle all the edge cases.

For now, I don't have a fix.

**Closed as completed** 2020-06-03 20:05 UTC
Labels: bug, wontfix
